import type {
  AdminPortalCompanyRecord,
  AdminPortalProjectRecord,
} from "../types/company";

export const adminPortalMockCompanies: AdminPortalCompanyRecord[] = [
  {
    id: "company-radiance",
    name: "Radiance Studio",
    primaryEmail: "hello@radiancestudio.co",
    primaryPhone: "(214) 555-0192",
    createdAt: "2026-01-08T10:00:00.000Z",
    projects: [
      {
        id: "project-radiance-website",
        companyId: "company-radiance",
        name: "Marketing Website Refresh",
        createdAt: "2026-01-10T12:00:00.000Z",
        currentPhase: "Design Revision",
        nextStep: "Approve homepage and service page wireframes",
        startDate: "2026-01-15",
        status: "active",
        targetLaunchDate: "2026-04-30",
        clientVisibleSummary:
          "The visual direction is approved. We are now finalizing the main marketing pages before development handoff.",
      },
      {
        id: "project-radiance-portal",
        companyId: "company-radiance",
        name: "Client Portal MVP",
        createdAt: "2026-02-01T08:00:00.000Z",
        currentPhase: "Planning",
        nextStep: "Confirm first-release features and internal admin workflow",
        startDate: "2026-02-05",
        status: "planned",
        targetLaunchDate: "2026-05-20",
        clientVisibleSummary:
          "The portal scope is currently being finalized. Once approved, the build will move into the first implementation phase.",
      },
    ],
  },
  {
    id: "company-gequence",
    name: "Gequence",
    primaryEmail: "team@gequence.com",
    primaryPhone: "(972) 555-0118",
    createdAt: "2026-02-12T14:00:00.000Z",
    projects: [
      {
        id: "project-gequence-landing",
        companyId: "company-gequence",
        name: "Landing Page Build",
        createdAt: "2026-02-13T09:00:00.000Z",
        currentPhase: "Development",
        nextStep: "Finish final responsive QA and polish animations",
        startDate: "2026-02-15",
        status: "active",
        targetLaunchDate: "2026-04-12",
        clientVisibleSummary:
          "The landing page build is in development and major sections are already in place. Remaining work is focused on responsiveness and launch polish.",
      },
    ],
  },
  {
    id: "company-northstar",
    name: "Northstar Legal Group",
    primaryEmail: "operations@northstarlegal.com",
    primaryPhone: "(469) 555-0177",
    createdAt: "2025-12-19T16:00:00.000Z",
    projects: [
      {
        id: "project-northstar-brand",
        companyId: "company-northstar",
        name: "Brand System Expansion",
        createdAt: "2026-01-04T15:00:00.000Z",
        currentPhase: "Completed Delivery",
        nextStep: "Schedule closeout review and archive final assets",
        startDate: "2026-01-07",
        status: "completed",
        targetLaunchDate: "2026-03-01",
        clientVisibleSummary:
          "The primary brand deliverables have been completed and delivered. The remaining work is a final wrap-up and documentation handoff.",
      },
    ],
  },
];

export const adminPortalMockProjectDetails: Record<
  string,
  AdminPortalProjectRecord
> = {
  "project-radiance-website": {
    id: "project-radiance-website",
    companyId: "company-radiance",
    name: "Marketing Website Refresh",
    createdAt: "2026-01-10T12:00:00.000Z",
    currentPhase: "Design Revision",
    nextStep: "Approve homepage and service page wireframes",
    startDate: "2026-01-15",
    status: "active",
    targetLaunchDate: "2026-04-30",
    clientVisibleSummary:
      "The visual direction is approved. We are now finalizing the main marketing pages before development handoff.",
    updates: [
      {
        id: "update-1",
        projectId: "project-radiance-website",
        title: "Homepage direction approved",
        description:
          "The client approved the updated homepage direction. We are now applying the same layout language to the remaining high-priority pages.",
        isVisibleToClient: true,
        createdAt: "2026-03-20T10:30:00.000Z",
        createdByAdminName: "Alex",
      },
      {
        id: "update-2",
        projectId: "project-radiance-website",
        title: "Content gaps identified",
        description:
          "The team flagged missing service copy and a few unclear CTAs. These items should be resolved before development begins.",
        isVisibleToClient: false,
        createdAt: "2026-03-22T14:00:00.000Z",
        createdByAdminName: "Jordan",
      },
    ],
    documents: [
      {
        id: "doc-1",
        projectId: "project-radiance-website",
        title: "Approved Sitemap",
        category: "Planning",
        description: "Current sitemap approved during planning review.",
        fileName: "approved-sitemap.pdf",
        fileType: "pdf",
        fileUrl: "#",
        fileSizeBytes: 182400,
        isVisibleToClient: true,
        createdAt: "2026-03-11T09:00:00.000Z",
        uploadedByAdminName: "Alex",
      },
      {
        id: "doc-2",
        projectId: "project-radiance-website",
        title: "Wireframe Notes",
        category: "Design",
        description: "Internal review notes for remaining wireframe changes.",
        fileName: "wireframe-notes.docx",
        fileType: "docx",
        fileUrl: "#",
        fileSizeBytes: 94400,
        isVisibleToClient: false,
        createdAt: "2026-03-18T16:15:00.000Z",
        uploadedByAdminName: "Jordan",
      },
    ],
    milestones: [
      {
        id: "milestone-1",
        projectId: "project-radiance-website",
        label: "Discovery complete",
        displayOrder: 1,
        status: "complete",
        completedAt: "2026-02-03T11:00:00.000Z",
        createdAt: "2026-01-20T11:00:00.000Z",
      },
      {
        id: "milestone-2",
        projectId: "project-radiance-website",
        label: "Homepage wireframes approved",
        displayOrder: 2,
        status: "current",
        completedAt: null,
        createdAt: "2026-03-02T11:00:00.000Z",
      },
    ],
  },
  "project-radiance-portal": {
    id: "project-radiance-portal",
    companyId: "company-radiance",
    name: "Client Portal MVP",
    createdAt: "2026-02-01T08:00:00.000Z",
    currentPhase: "Planning",
    nextStep: "Confirm first-release features and internal admin workflow",
    startDate: "2026-02-05",
    status: "planned",
    targetLaunchDate: "2026-05-20",
    clientVisibleSummary:
      "The portal scope is currently being finalized. Once approved, the build will move into the first implementation phase.",
    updates: [],
    documents: [],
    milestones: [],
  },
  "project-gequence-landing": {
    id: "project-gequence-landing",
    companyId: "company-gequence",
    name: "Landing Page Build",
    createdAt: "2026-02-13T09:00:00.000Z",
    currentPhase: "Development",
    nextStep: "Finish final responsive QA and polish animations",
    startDate: "2026-02-15",
    status: "active",
    targetLaunchDate: "2026-04-12",
    clientVisibleSummary:
      "The landing page build is in development and major sections are already in place. Remaining work is focused on responsiveness and launch polish.",
    updates: [
      {
        id: "update-3",
        projectId: "project-gequence-landing",
        title: "Tablet layout pass complete",
        description:
          "Tablet breakpoints have been reviewed and adjusted. Remaining QA is focused on small-screen spacing and footer behavior.",
        isVisibleToClient: true,
        createdAt: "2026-03-23T09:30:00.000Z",
        createdByAdminName: "Alex",
      },
    ],
    documents: [
      {
        id: "doc-3",
        projectId: "project-gequence-landing",
        title: "Launch Checklist",
        category: "Launch",
        description: "Internal pre-launch checklist draft.",
        fileName: "launch-checklist.pdf",
        fileType: "pdf",
        fileUrl: "#",
        fileSizeBytes: 113500,
        isVisibleToClient: false,
        createdAt: "2026-03-21T08:45:00.000Z",
        uploadedByAdminName: "Alex",
      },
    ],
    milestones: [
      {
        id: "milestone-3",
        projectId: "project-gequence-landing",
        label: "Approved visual direction",
        displayOrder: 1,
        status: "complete",
        completedAt: "2026-03-04T10:00:00.000Z",
        createdAt: "2026-02-28T10:00:00.000Z",
      },
      {
        id: "milestone-4",
        projectId: "project-gequence-landing",
        label: "Responsive QA complete",
        displayOrder: 2,
        status: "upcoming",
        completedAt: null,
        createdAt: "2026-03-19T10:00:00.000Z",
      },
    ],
  },
  "project-northstar-brand": {
    id: "project-northstar-brand",
    companyId: "company-northstar",
    name: "Brand System Expansion",
    createdAt: "2026-01-04T15:00:00.000Z",
    currentPhase: "Completed Delivery",
    nextStep: "Schedule closeout review and archive final assets",
    startDate: "2026-01-07",
    status: "completed",
    targetLaunchDate: "2026-03-01",
    clientVisibleSummary:
      "The primary brand deliverables have been completed and delivered. The remaining work is a final wrap-up and documentation handoff.",
    updates: [],
    documents: [],
    milestones: [],
  },
};
